name: wazo-number-condition-plugin
namespace: serge
version: 0.0.7
author: Serge Bayet
display_name: Number Condition
min_wazo_version: 24.00
plugin_format_version: 0
tags:
  - call-management
homepage: https://github.com/SergeBayet/wazo-number-condition-plugin

asterisk:
  config_files:
    extensions_extra.d/number-condition.conf:
      source: asterisk/extensions_extra.d/number-condition.conf
